/// Flutter icons WeatherIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData cloud_sun_rain_solid =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cloud_sun_solid =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cloud_rain_solid =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cloud_showers_heavy_solid =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cloud_solid = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cloud_moon_rain_solid =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cloud_moon_solid =
      IconData(0xe806, fontFamily: _kFontFam);
  static const IconData cloud_meatball_solid =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData wind_solid = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData bolt_solid = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData sun_solid = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData sun = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData tint_slash_solid =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData tint_solid = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData smog_solid = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData moon_solid = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData moon = IconData(0xe810, fontFamily: _kFontFam);
}
