name: dots_clock
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    git:
      url: git@github.com:domesticmouse/flutter_clock.git
      path: flutter_clock_helper
  text_to_path_maker: ^0.5.7
  fast_noise: ^0.1.3+1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf