name: cloom_clock
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    git:
      url: https://github.com/domesticmouse/flutter_clock
      path: flutter_clock_helper
  cupertino_icons: ^1.0.2
  # flare_flutter: 1.8.3
  flare_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
  assets:
    - assets/
    - assets/dark/
    - assets/light/